### ISSUE TITLE
Specifying weights for SurveyData as name of column

### ISSUE THREAD

**Issue by jgabry** [mitzimorris/mrp-kit#87]
Currently the weights have to actually be a numeric vector. For convenience should also allow just specifying which column contains the weights? 

Here's the current situation:

```r
# suppose weights are in column `wt`
SurveyData$new(data, weights = data$wt)
```

Should we allow this alternative? 

```r
SurveyData$new(data, weights = "wt")
```

**Comment by jgabry** [comment]
In fact, it would actually things easier for us if we _only_ allowed specifying the column name. That way we could then automatically exclude that column when we don't want it. Right now we don't actually know the column name of the weights variable and so we get warnings from validate() like 

```
Variable(s) 'wt' are available in the population but won't be used in the model  
```

It would be simpler to avoid that if we knew the column name of the weights variable. 

Thoughts about only allowing this form of specifying weights?

**Comment by lauken13** [comment]
Oops I missed this. Yes I think it's a good idea. More R centric too to have them tied in a dataframe rather than splitting up and relying on implicit ordering.
